---
title: "homework5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kernlab)
library(randomForest)
library(neuralnet)
ls("package:neuralnet")
library(ElemStatLearn)
library(ISLR)
library(e1071)
library(uskewFactors)
library(pls)
library(factoextra)
```

```{r}

SpamData = data(spam)
SpamData = spam
set.seed(12345)


train_spam = sample(1:nrow(SpamData), nrow(SpamData)*0.70)
test_spam = -train_spam
train_spam_data = spam[train_spam, ]
test_spam_data = spam[test_spam, ]
train_spam_data$spam <- as.character(train_spam_data$spam)
train_spam_data$spam <- as.factor(train_spam_data$spam)

# 3 entries
random_model_3 = randomForest(spam~., data=train_spam_data,mtry=3,ntree=1500)
random_model_3
#OOB 5.31%
random_pred_3 = predict(random_model_3, test_spam_data, type = "class") 
rand_test_error3=round(mean(random_pred_3 != test_spam_data$spam),4)
rand_test_error3
#0.0492


# 5 entries
random_model_5 = randomForest(spam~., data=train_spam_data,mtry=5,ntree=1500)
random_model_5
#OOB 4.81%
random_pred_5 = predict(random_model_5, test_spam_data, type = "class") 
rand_test_error_5=round(mean(random_pred_5 != test_spam_data$spam),4)
rand_test_error_5
#0.0427



#10 entries
random_model_10 = randomForest(spam~., data=train_spam_data,mtry=10,ntree=1500)
random_model_10
#OOB 5.22%
random_pred_10 = predict(random_model_10, test_spam_data, type = "class") 
rand_test_error10 = round(mean(random_pred_10 != test_spam_data$spam),4)
rand_test_error10
#0.0449


#20 entries
random_model_20 = randomForest(spam~., data=train_spam_data,mtry=20,ntree=1500)
random_model_20
#OOB 5.43%
random_pred_20 = predict(random_model_20, test_spam_data, type = "class") 
rend_test_error20 = round(mean(random_pred_20 != test_spam_data$spam),4)
rend_test_error20
#0.0492

oob_combined <- c(5.31,4.81,5.22,5.43)
test_error_combined <- c(0.0492,0.0427,0.0439,0.0492)


par(mfrow=c(1,2))

plot(oob_combined, main ="oob error" ,xlab = "1:entry 3 , 2:entry 5, 3:entry 10, 4:entry 20", col=c("blue","black","green","red"))

plot(test_error_combined, main ="test error" ,xlab = "1:entry 3 , 2:entry 5, 3:entry 10, 4:entry 20", col=c("blue","black","green","red"))

```


```{r}
set.seed(12345)
data("spam")
spam$spam<-as.numeric(spam$spam)-1



train_spam = sample(1:nrow(spam), nrow(spam)*0.70)
test_spam = -train_spam
train_spam_data = spam[train_spam, ]
test_spam_data = spam[test_spam, ]




n<-names(train_spam_data)
f <- as.formula(paste("spam ~", paste(n[!n %in% "spam"], collapse = " + ")))
nn <- neuralnet(f, data = train_spam_data, hidden = 1, err.fct = 'ce', linear.output = FALSE)

names(nn)
nn$result.matrix
round(nn$net.result[[1]])
nn_pred = round(compute(nn,test_spam_data[,1:57])$net.result[,1])
round(mean(test_spam_data$spam != nn_pred),4)

#0.0652
```



```{r}

set.seed(12345)


train <- sample(nrow(OJ),1000)

oj.train = OJ[train, ]
oj.test = OJ[-train, ]



svm.linear <- svm(Purchase ~ ., data = oj.train, kernel = "linear", cost = 0.01)
summary(svm.linear)


train.pred <- predict(svm.linear, oj.train)
table(oj.train$Purchase, train.pred)

train_error <- (98+75) / (539+75+98+288)

train_error

test.pred <- predict(svm.linear, oj.test)
table(oj.test$Purchase, test.pred)

test_error <- (2+3) / (36+3+2+29)

round(test_error,3)

svm.linear_1 <- svm(Purchase ~ ., data = oj.train, kernel = "linear", cost = 1)
summary(svm.linear_1)

train.pred_1 <- predict(svm.linear_1, oj.train)
table(oj.train$Purchase, train.pred_1)

train_error_1 <- (93+77) / (537+77+93+293)

train_error_1

test.pred_1 <- predict(svm.linear_1, oj.test)
table(oj.test$Purchase, test.pred_1)

test_error_1 <- (2+4) / (35+4+2+29)

test_error_1

round(test_error_1,2)

svm.linear_2 <- svm(Purchase ~ ., data = oj.train, kernel = "linear", cost = 5)
summary(svm.linear_2)

train.pred_2 <- predict(svm.linear_2, oj.train)
table(oj.train$Purchase, train.pred_2)

train_error_2 <- (94+73) / (541+73+94+292)

train_error_2

test.pred_2 <- predict(svm.linear_2, oj.test)
table(oj.test$Purchase, test.pred_2)

test_error_2 <- (2+3) / (37+3+2+28)

test_error_2

round(test_error_2,3)


svm.linear_3 <- svm(Purchase ~ ., data = oj.train, kernel = "linear", cost = 10)
summary(svm.linear_3)

train.pred_3 <- predict(svm.linear_3, oj.train)
table(oj.train$Purchase, train.pred_3)

train_error_3 <- (90+76) / (538+76+90+296)

train_error_3

test.pred_3 <- predict(svm.linear_3, oj.test)
table(oj.test$Purchase, test.pred_3)

test_error_3 <- (2+4) / (37+4+2+27)

test_error_3

round(test_error_3,3)



oj_train_error_combined <- c(train_error,train_error_1,train_error_2,train_error_3)

oj_test_error_combined <- c(test_error,test_error_1,test_error_2,test_error_3)

par(mfrow=c(1,2))

plot(oj_train_error_combined, main ="oj_train_error" ,xlab = "1:cost 0.01 , 2:cost 1, 3:cost 5, 4:cost 10", col=c("blue","black","green","red"))

plot(oj_test_error_combined, main ="oj_test_error" ,xlab = "1:cost 0.01 , 2:cost 1, 3:cost 5, 4:cost 10", col=c("blue","black","green","red"))

tune_out <- tune(svm, Purchase ~ ., data = oj.train, kernel = "linear", ranges = list(cost = 10^seq(-2, 1, by = 0.25)))

summary(tune_out)

#0.01 is the omptimal cost 


#radial kernel

svm.radial <- svm(Purchase ~ ., data = oj.train, kernel = "radial",cost=0.01)
summary(svm.radial)

train.pred_radial <- predict(svm.radial, oj.train)
table(oj.train$Purchase, train.pred)

train_error_radial <- (98+75) / (539+75+98+288)

train_error_radial

test.pred_radial <- predict(svm.radial, oj.test)
table(oj.test$Purchase, test.pred_radial)

test_error_radial <- (4+3) / (36+3+4+27)

round(test_error_radial,1)

svm.radial_1 <- svm(Purchase ~ ., data = oj.train, kernel = "radial", cost = 1)
summary(svm.radial_1)

train.pred_1_radial <- predict(svm.radial_1, oj.train)
table(oj.train$Purchase, train.pred_1_radial)

train_error_1_radial <- (102+56) / (558+56+102+284)

train_error_1_radial

test.pred_1_radial <- predict(svm.radial_1, oj.test)
table(oj.test$Purchase, test.pred_1_radial)

test_error_1_radial <- (3+4) / (36+4+3+27)

test_error_1_radial

svm.radial_2 <- svm(Purchase ~ ., data = oj.train, kernel = "radial", cost = 5)
summary(svm.radial_2)

train.pred_2_radial <- predict(svm.radial_2, oj.train)
table(oj.train$Purchase, train.pred_2_radial)

train_error_2_radial <- (102+51) / (563+51+102+284)

train_error_2_radial

test.pred_2_radial <- predict(svm.radial_2, oj.test)
table(oj.test$Purchase, test.pred_2_radial)

test_error_2_radial <- (4+3) / (36+3+4+27)

test_error_2_radial



svm.radial_3 <- svm(Purchase ~ ., data = oj.train, kernel = "radial", cost = 10)
summary(svm.radial_3)

train.pred_3_radial <- predict(svm.radial_3, oj.train)
table(oj.train$Purchase, train.pred_3_radial)

train_error_3_radial <- (100+53) / (561+53+100+286)

train_error_3_radial

test.pred_3_radial <- predict(svm.radial_3, oj.test)
table(oj.test$Purchase, test.pred_3_radial)

test_error_3_radial <- (4+4) / (35+4+4+27)

test_error_3_radial

round(test_error_3_radial,3)



oj_train_error_combined_radial <- c(train_error_radial,train_error_1_radial,train_error_2_radial,train_error_3_radial)

oj_test_error_combined_radial <- c(test_error_radial,test_error_1_radial,test_error_2_radial,test_error_3_radial)

par(mfrow=c(1,2))

plot(oj_train_error_combined_radial, main ="oj_train_error_radial" ,xlab = "1:cost 0.01 , 2:cost 1, 3:cost 5, 4:cost 10", col=c("blue","black","green","red"))

plot(oj_test_error_combined_radial, main ="oj_test_error_radial" ,xlab = "1:cost 0.01 , 2:cost 1, 3:cost 5, 4:cost 10", col=c("blue","black","green","red"))

tune_out_radial <- tune(svm, Purchase ~ ., data = oj.train, kernel = "radial", ranges = list(cost = 10^seq(-2, 1, by = 0.25)))

summary(tune_out_radial)



#0.01 is the optimal point 

#polynomoal 

svm.poly <- svm(Purchase ~ ., kernel = "polynomial", data = oj.train, degree = 2)
summary(svm.poly)

train.pred_poly <- predict(svm.poly, oj.train)
table(oj.train$Purchase, train.pred_poly)

train_error_poly <- (140+45) / (569+45+140+246)

train_error_poly

test.pred_poly <- predict(svm.poly, oj.test)
table(oj.test$Purchase, test.pred_poly)

test_error_poly <- (2+6) / (37+6+2+25)

round(test_error_poly,3)

svm.poly_1 <- svm(Purchase ~ ., kernel = "polynomial", data = oj.train, degree = 2)
summary(svm.poly)


error_combined <- c(train_error_poly,test_error_poly)

plot(error_combined, main ="train & test error of polynomial (degree =2)" ,xlab = "1: train error, 2: test error", col=c("brown","black"))

```

```{r}

banknote <- get(load('~/Desktop/SwissBankNotes.rdata'))

pca1<-prcomp(as.matrix(banknote), center = T)
summary(pca1)

fviz_pca_biplot(pca1, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )

real <- banknote[1:100,]

pca2<-prcomp(as.matrix(real), center = T)
summary(pca2)

fviz_pca_biplot(pca2, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )


fake <-banknote[101:200,]
pca3<-prcomp(as.matrix(fake), center = T)
summary(pca3)

fviz_pca_biplot(pca3, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )


```



